import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";

import Footer from "./components/Footer/Footer";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="logo d-flex justify-content-center align-items-center">
          {/* <Image
            src="/images/logo.png"
            width={100}
            height={70}
            alt="scan logo"
            priority
          /> */}
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
